### ISSUE TITLE
Small errors in the make_sce.R script

### ISSUE THREAD

**Issue by zhen-fu** [vari-bbc/methylation_array#2]
There is a small error that needs to be fixed.

**Comment by genomics-kl** [comment]
Is this supposed to be for the RNAseq workflow? I don't think there is a make_sce.R script in this repo. Also, what is the error?

**Comment by zhen-fu** [comment]
My bad, there is a small error in make_sesame_SE.R. The error was a column name in line 12-15 of make_sesame_SE.R. I ran this workflow two weeks ago. It did not work. I will fix it and do a pull request.
